openapi: 3.0.0
servers:
  - description: SwaggerHub API Documentation
    url: https://virtserver.swaggerhub.com/YoussefBouali/DataMining_Project/1.0.0
info:
  description: DataMining Project API
  version: "1.0.0"
  title: DataMining Project
  contact:
    email: mr.boualiyoussef@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /search_similar_products:
    get:
      summary: Search for similar products
      description: Search for similar products based on the product name.
      parameters:
        - name: product_name
          in: query
          required: true
          description: The name of the product to search for similar products.
          schema:
            type: string
      responses:
        '200':
          description: A list of similar products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nom:
                      type: string
                    website:
                      type: string
                    mean_price:
                      type: number
                    min_price:
                      type: number
                    max_price:
                      type: number
                    count:
                      type: integer
        '400':
          description: Product name is required
        '404':
          description: No similar products found
  /all_promotions_par_categorie:
    get:
      summary: Analyze promotions by category
      description: This endpoint analyzes promotions by category.
      responses:
        '200':
          description: A list of promotions by category
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    category:
                      type: string
                    promotion:
                      type: string
                    count:
                      type: integer
  /analyse_top_product:
    get:
      summary: Get top product with price variations
      description: Fetch the top product and its price variations across different websites.
      responses:
        '200':
          description: Top product and its price variations
          content:
            application/json:
              schema:
                type: object
                properties:
                  top_product:
                    type: string
                  price_variations:
                    type: array
                    items:
                      type: object
                      properties:
                        website:
                          type: string
                        prix:
                          type: number
  /plot_analyse_top_product:
    get:
      summary: Plot price variations for the top product
      description: Generates and returns a plot for the price variations of the top product.
      responses:
        '200':
          description: A plot of price variations for the top product
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /analyse_promotions:
    get:
      summary: Analyze promotions by category and type
      description: Analyze and return promotions categorized by type.
      responses:
        '200':
          description: Top promotions by category and type
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    category:
                      type: string
                    promotion:
                      type: string
                    count:
                      type: integer
  /plot_analyse_promotions:
    get:
      summary: Plot promotions by category and promotion type
      description: Generate and return a plot of promotions categorized by type.
      responses:
        '200':
          description: A plot of promotions by category and type
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /products_by_date:
    get:
      summary: Analyze products by date and website
      description: Analyze products by date and website with details on price.
      responses:
        '200':
          description: Products by date and website with price statistics
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nom:
                      type: string
                    website:
                      type: string
                    min:
                      type: number
                    mean:
                      type: number
                    max:
                      type: number
                    count:
                      type: integer
  /plot_products_by_date:
    get:
      summary: Plot price variations by date for products
      description: Generate and return a plot for the price variations by date for top products.
      responses:
        '200':
          description: A plot of price variations by date for the top products
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /site_grouped_sites:
    get:
      summary: Analyze Products grouped by website
      description: Group Products by website and calculate price variations.
      responses:
        '200':
          description: Price variations grouped by website
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    website:
                      type: string
                    mean:
                      type: number
                    min:
                      type: number
                    max:
                      type: number
  /plot_site_grouped_sites:
    get:
      summary: Plot price variations grouped by website
      description: Generate and return a plot for price variations grouped by website.
      responses:
        '200':
          description: A plot of price variations grouped by website
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary